# Generated by Django 3.0.1 on 2022-04-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onadata',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='onadata',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='onadata',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='onadata',
            name='status',
        ),
    ]
