# Generated by Django 3.0.1 on 2022-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onapp', '0002_auto_20220411_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='onadata',
            name='employment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onadata',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onadata',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='onadata',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
