# Generated by Django 3.0.1 on 2022-04-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onapp', '0004_auto_20220411_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startdate',
            name='end_date',
        ),
    ]
