# Generated by Django 3.0.1 on 2022-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onapp', '0005_remove_startdate_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startdate',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
